Chess figures
twohoursonelife/OneLifeData7 pull request #155
Opened 2024-05-10 13:36 UTC by SenMooo

Adds chess figures. 

Last use for chisel was added manually.

2024-05-14 13:44 UTC, connorhsm requested changes
Please [squash your commits](https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together) now that dev work is complete. A single commit along "Add chess pieces" will do.

2024-05-17 19:05 UTC, connorhsm approved these changes, later dismissed

2024-05-18 20:37 UTC, zabala6 commented
Tested locally and i didn't find any inconsistency. I like that we can put the chess figures to the box. Good job!

2024-06-27 16:45 UTC, risvh approved these changes
Thank you, nice work!

2024-06-27 16:46 UTC, merged