Update of Sandstone Windows, Introducing Sandstone Windowsills, and Arches
twohoursonelife/OneLifeData7 pull request #157
Opened 2024-05-11 20:14 UTC by sidraba

This pull request brings several additions to our walls: sandstone window rework, sandstone windowsills for both ancient and regular walls, and sandstone arches, including normal and left and right sideway arches.

### Summary of Changes
**New Window Sprites**: I've replaced the old sandstone window sprites with updated versions that are nicer and will probably be used more in builds.
**Windowsills**: Added sandstone windowsills for both ancient and regular walls, as sandstone windows did not look good with standard windowsills, I used new art from anafae to blend in sandstone wall better. Sandstone windowsills are made of sandstone and only has one slot due to size. And yes, both ancient and normal sandstone windowsills can hold calico cat.
**Arches**: Introduced sandstone arches, including normal and left and right sideway variants. 

all art by amazing anafae

![screen00052](https://github.com/twohoursonelife/OneLifeData7/assets/163928298/4bc37f31-61c3-4fd7-958d-868d4ca8dbd1)

2024-05-14 13:47 UTC, connorhsm requested changes
Please [squash your commits](https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together) now that dev work is complete. I would suggest commits:
- Update Sandstone windows
- Add Sandstone windowsills and arches

2024-05-18 20:32 UTC, zabala6 commented
Tested locally and i didn't find any inconsistency. Good job!

2024-05-19 01:01 UTC, connorhsm approved these changes

2024-07-20 18:23 UTC, risvh commented
Thank you! I have cherry-picked and made some changes. Asked anafae's help to polish the texture of the arches. And chose the normal wooden windowsill over a new sandstone one. I think the difference in the looks is not big enough to warrant having the sandstone wall windowsill different than other windowsills.

2024-07-20 18:23 UTC, closed without merging